import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/utils/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MDT - Police",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen`}
      >
        <Sidebar/>
        <div className="flex-1 overflow-y-auto w-full p-2">
          {children}
        </div>
      </body>
    </html>
  );
}
